name: Deploy to hostido

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Cache build
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-build-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('**/pnpm-lock.yaml') }}-
            ${{ runner.os }}-build-
      - name: Cache images
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/node_modules/.cache/next-export-optimize-images
          key: ${{ runner.os }}-images-${{ hashFiles('./public/images/**') }}
          restore-keys: |
            ${{ runner.os }}-images-
      - name: Build with Next.js
        run: pnpm run build
        env:
          NEXT_PUBLIC_FORM_ACCESS_KEY: ${{ env.NEXT_PUBLIC_FORM_ACCESS_KEY }}
          NEXT_PUBLIC_GA_ID: ${{ env.NEXT_PUBLIC_GA_ID }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: build-files
          path: ./out

  # Deployment job
  deploy:
    environment:
      name: main
      url: wielmi.pl
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-files
          path: ./build

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Deploy to server
        run: |
          scp -P $SSH_PORT -r ./build/* $SSH_USERNAME@$SSH_HOST:~/domains/wielmi.pl/public_html
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
